# Generated by Django 4.2.14 on 2024-10-07 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurans', '0003_restaurans_description'),
        ('menu', '0002_dish_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurans.restaurans', verbose_name='Ресторан'),
        ),
    ]
