# Generated by Django 4.2.14 on 2025-05-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_label_dish_calories_dish_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Метку', 'verbose_name_plural': 'Метки'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='carbohydrates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='fats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='proteins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
