# Generated by Django 4.2.14 on 2025-05-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_label_options_alter_dish_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка в %'),
        ),
    ]
