# Generated by Django 4.2.14 on 2025-05-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_dish_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji или Unicode-иконка', max_length=10),
        ),
    ]
