# Generated by Django 4.2.14 on 2025-05-19 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0008_label_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
                ('preference_type', models.CharField(choices=[('like', 'Люблю'), ('dislike', 'Не люблю'), ('allergy', 'Аллергия')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
