# Generated by Django 4.2.14 on 2025-05-19 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0009_ingredientpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('like', 'Нравится'), ('dislike', 'Не нравится'), ('diet', 'Диета'), ('allergy', 'Аллергия')], max_length=10)),
            ],
            options={
                'verbose_name': 'Предпочтение',
                'verbose_name_plural': 'Предпочтения',
            },
        ),
        migrations.RemoveField(
            model_name='label',
            name='icon',
        ),
        migrations.DeleteModel(
            name='IngredientPreference',
        ),
        migrations.AddField(
            model_name='labelpreference',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.label'),
        ),
        migrations.AddField(
            model_name='labelpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='labelpreference',
            unique_together={('user', 'label', 'preference_type')},
        ),
    ]
