# Generated by Django 4.2.14 on 2025-05-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurans', '0008_restaurans_end_time_restaurans_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections_images', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подборка',
                'verbose_name_plural': 'Подборки',
                'db_table': 'restCollections',
            },
        ),
        migrations.CreateModel(
            name='SelectionRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurans.restaurans')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_collections.selection')),
            ],
            options={
                'verbose_name': 'Ресторан в подборке',
                'verbose_name_plural': 'Рестораны в подборках',
                'unique_together': {('selection', 'restaurant')},
            },
        ),
        migrations.AddField(
            model_name='selection',
            name='restaurants',
            field=models.ManyToManyField(related_name='selections', through='rest_collections.SelectionRestaurant', to='restaurans.restaurans', verbose_name='Рестораны'),
        ),
    ]
