# Generated by Django 4.2.14 on 2025-01-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurans', '0005_alter_restaurans_image'),
        ('orders', '0003_remove_order_total_price_order_payment_on_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_restaurant', to='restaurans.restaurans', verbose_name='Ресторан'),
        ),
    ]
