# Generated by Django 4.2.14 on 2025-03-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='entrance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
    ]
