# Generated by Django 4.2.14 on 2025-04-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_apartment_order_entrance_order_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('restaurant_confirmed', 'Ресторан подтвердил'), ('cooking', 'Готовится'), ('awaiting_delivery', 'Ожидает курьера'), ('on_the_way', 'В пути'), ('delivered', 'Доставлен'), ('canceled', 'Отменён')], default='processing', max_length=50, verbose_name='Статус'),
        ),
    ]
