# Generated by Django 4.2.14 on 2025-05-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_latitude_customuser_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disliked_ingredients',
            field=models.TextField(blank=True, help_text='Что вы не любите (например, лук, каперсы)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked_ingredients',
            field=models.TextField(blank=True, help_text='Что вы любите (например, сливки, сыр, грибы)', null=True),
        ),
    ]
