# Generated by Django 4.2.14 on 2025-05-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_disliked_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='latitude',
            new_name='last_latitude',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='longitude',
            new_name='last_longitude',
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
