# Generated by Django 4.2.14 on 2025-05-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_latitude_customuser_last_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_longitude',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='priority',
            field=models.FloatField(default=0.0, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='transport_mode',
            field=models.CharField(choices=[('foot', 'Пешком'), ('bicycle', 'На велосипеде'), ('scooter', 'На самокате'), ('motorcycle', 'На мотоцикле'), ('car', 'На машине')], default='foot', max_length=20, verbose_name='Способ передвижения'),
        ),
    ]
