# Generated by Django 4.2.14 on 2025-03-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promotion_end_time_alter_promotion_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_time',
            field=models.DateField(verbose_name='Дата конца акции'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_time',
            field=models.DateField(verbose_name='Дата начала акции'),
        ),
    ]
