# Generated by Django 4.2.14 on 2025-04-20 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurans', '0008_restaurans_end_time_restaurans_start_time'),
        ('promotions', '0004_alter_promotion_end_time_alter_promotion_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название акции')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('start_time', models.DateField(verbose_name='Дата начала')),
                ('end_time', models.DateField(verbose_name='Дата конца')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotion_request_images', verbose_name='Изображение')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено админом')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurans.restaurans', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Заявка на акцию',
                'verbose_name_plural': 'Заявки на акции',
            },
        ),
    ]
