# Generated by Django 4.2.14 on 2025-05-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_promotionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionrequest',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
    ]
