# Generated by Django 4.2.14 on 2024-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurans',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
