# Generated by Django 4.2.14 on 2024-10-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurans', '0004_restaurans_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurans',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants_images', verbose_name='Изображение'),
        ),
    ]
