# Generated by Django 4.2.14 on 2025-04-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurans', '0007_restaurans_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurans',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец работы'),
        ),
        migrations.AddField(
            model_name='restaurans',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало работы'),
        ),
    ]
